FROM node:latest

# Create app directory
RUN mkdir -p /home/app
WORKDIR /home/app

# Install app dependencies
COPY package*.json /home/app/
RUN npm ci

# Bundle app source
COPY . /home/app

# Start server
EXPOSE 3000
CMD [ "npm", "start" ]
